# -*- coding: utf-8 -*-
# vim: ft=yaml

# common mutualized values
{% set version_full = "1.12.0" %}
{% set version_full_deb = version_full ~ "-0~" ~ grains['oscodename'] %}
{% set repo_name = "deb https://apt.dockerproject.org/repo debian-" ~ grains['oscodename'] ~ " main" %}


docker:
  pkg: docker-engine
  service:
    name: docker
  repo:
    humanname: 'Docker ASF Debian repository'
    name: {{ repo_name }}
    file: /etc/apt/sources.list.d/docker.list
    keyid: 58118E89F3A912897C070ADBF76221572C52609D
    keyserver: p80.pool.sks-keyservers.net
  version:
    full: {{ version_full }}
    full_deb: {{ version_full_deb }}
  compose:
    version: 1.8.0
